# Generated by Django 5.1.3 on 2024-11-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_skill_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company_manager', models.CharField(max_length=255)),
                ('manager_email', models.CharField(max_length=255)),
            ],
        ),
    ]
