# Generated by Django 5.1.3 on 2024-11-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not set', 'Not Set')], default='not set', max_length=255),
        ),
    ]
